/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package lab2;

/**
 *
 * @author jabot_000
 */
import java.awt.*;
import java.util.Stack;

public class Lab3 extends javax.swing.JFrame {
   //Jframe frame = new Jframe("test");
   

   /**
    * Creates new form JFrame
    */
   private String nums;
   private String out;
   public Lab3() {
      initComponents();
      nums = "";
      out = "";
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
   
      goButton = new javax.swing.JButton();
      Input = new javax.swing.JTextField();
      Output = new javax.swing.JTextField();
   
      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
   
      goButton.setText("Go");
      goButton.addActionListener(
         new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               goButtonActionPerformed(evt);
            }
         });
   
      Input.setText("");
   
      Output.setText("");
   
      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(636, 636, 636)
                        .addComponent(goButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(529, 529, 529)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Input, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(Output))))
                .addContainerGap(531, Short.MAX_VALUE))
         );
      layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Input, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294)
                .addComponent(goButton)
                .addGap(128, 128, 128)
                .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
         );
   
      pack();
   }// </editor-fold>                        

   private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
       //srv.read(Input.getText());
      nums = Input.getText();
      this.reverse();
      //System.out.println(nums);
       
   } 
   public void reverse(){
      Stack<Character> s = new Stack<Character>();
      for(int i=0; i<nums.length(); ++i){
         s.push(nums.charAt(i));
      }
      for(int i=0; i<nums.length(); ++i){
        out +=  s.pop();
      }
      //System.out.println(out);
      Output.setText(out);
   }                                       
   

   
   

    // Variables declaration - do not modify                     
   private javax.swing.JTextField Input;
   private javax.swing.JTextField Output;
   private javax.swing.JButton goButton;
    // End of variables declaration                   
}
